ring_doorbell/__init__.py, ring_doorbell/const.py
=> Make flake8 happy

README.md, ring_doorbell/__init__.py
Refactored and updated documentation
=> Refactored and updated documentation

.hound.yml, .travis.yml, pylintrc, requirements.txt, ring_doorbell/__init__.py, ring_doorbell/const.py, ring_doorbell/utils.py, setup.py, tox.ini
=> Implemented travis, tox tests

pylintrc, ring_doorbell/__init__.py
=> Merging from dev

ring_doorbell/__init__.py
Fix range for battery information to return 0-100 values
Fixes issue: #6
=> Fix range for battery information

README.md, ring_doorbell/__init__.py, ring_doorbell/const.py, setup.py
**BREAK CHANGES** (not ready to commit yet)
This PR is basically a rewrite from the project which nows allows to treat the devices as objects and not as functions anymore. This change will introduce more transparency to the user.
```python
In [1]: from ring_doorbell import Ring
In [2]: myring = Ring('user@email.com', 'password')
In [3]: myring.devices
Out[3]: 
{'chimes': [<RingChime: Downstairs>],
'doorbells': [<RingDoorBell: Front Door>]}
In [4]: myring.chimes
Out[4]: [<RingChime: Downstairs>]
In [5]: myring.doorbells
Out[5]: [<RingDoorBell: Front Door>]
In [6]: mychime = myring.chimes[0]
In [7]: mychime.
mychime.account_id         mychime.firmware           mychime.linked_tree        mychime.subscribed_motions 
mychime.address            mychime.id                 mychime.longitude …
```
=> Refactored project to make it more Pythonish and transparent

README.md, ring_doorbell/__init__.py, ring_doorbell/const.py, setup.py
**BREAK CHANGES** 
This PR is basically a rewrite from the project which nows allows to treat the devices as objects and not as functions anymore. This change will introduce more transparency to the user.
```python
In [1]: from ring_doorbell import Ring
In [2]: myring = Ring('user@email.com', 'password')
In [3]: myring.devices
Out[3]: 
{'chimes': [<RingChime: Downstairs>],
'doorbells': [<RingDoorBell: Front Door>]}
In [4]: myring.chimes
Out[4]: [<RingChime: Downstairs>]
In [5]: myring.doorbells
Out[5]: [<RingDoorBell: Front Door>]
In [6]: mychime = myring.chimes[0]
In [7]: mychime.
mychime.account_id         mychime.firmware           mychime.linked_tree        mychime.subscribed_motions 
mychime.address            mychime.id                 mychime.longitude          mychime.timezone …
```
=> Bump version to 0.1.0 - **BREAK CHANGES**

README.md, ring_doorbell/__init__.py, ring_doorbell/utils.py
Via this method, we will have an attribute to store the response received from the notification request and to save the timestamp for how much time the request is 'on-going' or 'valid'. 
This will be useful in cases where a ring happened but we want to keep the notification active for the next 180 seconds (which is the default).
=> Introduced check_alerts() method

README.rst
Added example from recording_url() method
=> Added new example

ring_doorbell/__init__.py, ring_doorbell/utils.py, tests/test_ring.py
Extended unittest coverage to check_alerts
=> Extended unittest coverage to check_alerts

ring_doorbell/__init__.py, ring_doorbell/const.py, ring_doorbell/utils.py, setup.py, tests/test_ring.py, tests/test_ring_utils.py
- Introduced the ability to reuse token between multiple objects to avoid duplicated connections/authentications on Ring API servers.
=> version 0.1.3

ring_doorbell/utils.py, tests/test_ring.py, tests/test_ring_utils.py
* Increased unit test coverage
* Removing unittest temp files using cleanup() method
=> Cleanup tests

README.rst
=> Fixes #40 - Dropped has_subscription attr

ring_doorbell/__init__.py, ring_doorbell/utils.py
=> Fixed traceback when req.status_code is None

ring_doorbell/doorbot.py
=> Changed from warning to logger.debug

README.rst, ring_doorbell/__init__.py, ring_doorbell/doorbot.py, ring_doorbell/utils.py, scripts/ringcli.py, setup.py
- Introduced ring_cli.py script
- Fixes some bugs and enhancements
- Add ability to inform attribute `older_than` to the `history()` method. Thanks to @troopermax #63
=> Version 0.1.7

ring_doorbell/doorbot.py, scripts/ringcli.py, setup.py
* Added the ability to check if account has the Ring subscription active since it is now enforced by Ring in order to use the methods `recording_download()` and `recording_url()` https://github.com/tchellomello/python-ring-doorbell/issues/71
Many thanks to @arsaboo for your help on testing this.
=> Version 0.1.8

ring_doorbell/__init__.py, ring_doorbell/doorbot.py, ring_doorbell/utils.py, setup.py
Changelog:
@andrewkress  - only save token to disk if reuse session is true #81
@tchellomello - Getting TypeError #86
=> Version 0.2.0

ring_doorbell/__init__.py, ring_doorbell/const.py, setup.py, tests/fixtures/ring_oauth.json, tests/test_base.py
Ring added an OAUTH Bearer authentication on their services. 
This patch added support to the new authentication model 
**TODO**:
[x] fix unittests
**Note**: Ring started using **Pinned Certificates** on their Android app. 
Fixes: #94 
Many thanks to everyone that reported this issue and one special shout to @davglass  for the heads up and pointing the workflow on this code/project. 
To test it, it should work the same way. Can anyone provide any feedback it this addressed the authentication issues?
=> Added oauth bearer token authentication to Ring

ring_doorbell/__init__.py, ring_doorbell/chime.py, ring_doorbell/const.py, ring_doorbell/doorbot.py, ring_doorbell/utils.py, setup.py, tests/fixtures/ring_oauth.json, tests/test_base.py
* Updated Ring authentication method to OAUTH base
Many thanks to @davglass for reporting this issue and for @rbrtio, @vickyg3, @cathcartd, and @dshokouhi for testing the fix.
=> Version 0.2.1

ring_doorbell/doorbot.py, setup.py
- Support for Spotlight Battery cameras with multiple battery bays #106 (@evanjd)
Many thanks for your first contribution @evanjd!!
=> Version 0.2.2

ring_doorbell/__init__.py, ring_doorbell/doorbot.py, tests/test_ring.py, tests/test_ring_utils.py
=> Fixed pylint and test errors

ring_doorbell/__init__.py, ring_doorbell/chime.py, ring_doorbell/const.py, ring_doorbell/doorbot.py, ring_doorbell/stickup_cam.py
update user agent typo which caused a new http 406 error
=> fix R1705: Unnecessary elif after return (no-else-return)

requirements.txt
Fixes requirements.txt to avoid issues in HA
```
2019-12-27 12:56:38 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config.py", line 761, in async_process_component_config
platform = p_integration.get_platform(domain)
File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 232, in get_platform
f"{self.pkg_path}.{platform_name}"
File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 953, in …
```
=> Fixed requirements.xt

ring_doorbell/__init__.py, ring_doorbell/auth.py, ring_doorbell/const.py
Compatibility with Python 2 (old-school typing syntax in docstrings); fix for OAuth.SCOPE - changed to a list to match what oauthlib expects (credit: @steve-gombos)
Fixes: #162
=> Fixes for tchellomello/python-ring-doorbell#162

ring_doorbell/__init__.py, ring_doorbell/const.py
=> Implemented timeouts for HTTP requests methods

ring_doorbell/__init__.py
Adds the use of `expires_in` from the oauth token to avoid getting new tokens too often.
Fixes #160
I'm not sure if refreshing at the exact time is the proper way to do it, maybe adding a 10s offset would avoid refresh issues.
=> Use auth expires_in to refresh oauth tokens

.travis.yml, ring_doorbell/__init__.py
* Fixed tox lint issues
* Simplified `datetime` modules import
* Restored if condition removed by mistake
* Added Python 3.7.0 to Travis + Lint
=> Fixed logic and simplified module imports

ring_doorbell/__init__.py, ring_doorbell/const.py, ring_doorbell/doorbot.py
=> Video download fix

README.rst, ring_doorbell/__init__.py, ring_doorbell/auth.py, ring_doorbell/chime.py, ring_doorbell/const.py, ring_doorbell/doorbot.py, ring_doorbell/generic.py, ring_doorbell/utils.py, setup.py, test.py, tests/test_base.py, tests/test_ring.py, tests/test_ring_utils.py
DRAFT
Overview
This change is from discussions of previous OAuth issues. This is a large change, and I don't think this solution is 100%, but I want to get it in front of some more eyes since there are some features I wasn't familiar with, for example push_token_notify_url, etc... and see if anyone has some input or thoughts.  
- Removed several properties, methods, and constructor params
- Moved cache file logic to Auth, refactored the cache file to store the OAuth lib token response and alerts from the Ring API
- Moved bulk of Query logic into Auth, kept the definition to reduce impact of changes to device classes
- Added query method, which is pretty similar to the query method from the Ring class, uses the OAuth2Session for requests.  Will refresh token if a token expired exception is …
=> Auth and ring class refactor

docs/source/index.rst
=> Pushes new documentation to (http://python-ring-doorbell.readthedocs.io/)

.github/workflows/ci.yml, ring_doorbell/__init__.py, ring_doorbell/auth.py
TravisCI.org is going away sometime soon. I think they want folks to use their ".com" product instead. This PR just swaps to using GitHub Actions as it's free for open-source and works pretty well.
=> [dist] Use GitHub Actions

ring_doorbell/doorbot.py
Reworked a little bit the logic introduced on the #218 and fixed my merging typo
=> get_snapshot() logic to be compliant with legacy

.flake8, .pre-commit-config.yaml, poetry.lock, pyproject.toml, ring_doorbell/cli.py, ring_doorbell/generic.py, ring_doorbell/ring.py, scripts/changeloggenerator.py, test.py, tests/fakes.py, tests/fixtures/ring_doorbots.json, tests/test_cli.py, tests/test_ring.py, tox.ini
Add tests to the cli
The previous ringcli.py logic that did thing with videos had quite a few issues which are now fixed
=> Add tests for cli and fix issues with videos

pyproject.toml, ring_doorbell/doorbot.py
To fix [HA issue](https://github.com/home-assistant/core/issues/106143)
=> Fix history timeformat and bump to 0.8.5

README.rst
Added thank note to Carles Pina for creating and maintaining the Debian package.
https://tracker.debian.org/pkg/python-ring-doorbell
=> Thank note for Debian package

ring_doorbell/__init__.py, ring_doorbell/cli.py, ring_doorbell/event.py, ring_doorbell/generic.py, ring_doorbell/listen.py, ring_doorbell/listen/__init__.py, ring_doorbell/listen/eventlistener.py, ring_doorbell/listen/listenerconfig.py, ring_doorbell/ring.py, tests/test_cli.py, tests/test_listen.py, tox.ini
Breaking change to the `listen` api.
=> Allow ring listener to be configurable

ring_doorbell/__init__.py, ring_doorbell/auth.py, ring_doorbell/cli.py, ring_doorbell/const.py, ring_doorbell/other.py, ring_doorbell/ring.py, tests/conftest.py, tests/fixtures/ring_devices.json, tests/fixtures/ring_intercom_settings.json, tests/fixtures/ring_intercom_users.json, tests/test_other.py, tests/test_ring.py
Another PR for Intercom, forked from andrew-rinato.
- Add test and test data for Intercom
- Real world test of Open Door with different user_id: I made it as a function param so a real user_id can be passed, if a fake one is provided the app just says "Shared User", without error.
Please let me know if something needs to be fixed, I promise this PR will not be abandoned. :)
=> Updated Intercom Support (2024)

README.rst, test.py
Fixes https://github.com/tchellomello/python-ring-doorbell/issues/267 https://github.com/tchellomello/python-ring-doorbell/issues/315 https://github.com/tchellomello/python-ring-doorbell/issues/356
=> Fix readme example and add to test.py

ring_doorbell/generic.py, ring_doorbell/other.py, ring_doorbell/ring.py, tests/fixtures/ring_devices.json
Fixes HA issue with non supported third party devices in `other` family.
https://github.com/home-assistant/core/issues/114334
=> Fix issue with third party devices returned in the group other

ring_doorbell/cli.py
=> Fix cli listen command on windows

.pre-commit-config.yaml, ring_doorbell/cli.py, ring_doorbell/ring.py, tests/test_cli.py
=> Add cli command to open door on intercom

.github/workflows/ci.yml, README.rst, pyproject.toml, ring_doorbell/__init__.py, ring_doorbell/cli.py, ring_doorbell/listen/__init__.py, tests/conftest.py, tests/test_cli.py, tests/test_listen.py, uv.lock
Now the event listener is stable it does not need to be behind an optional installation extra.
=> Event listener capability enabled by default

ring_doorbell/doorbot.py, ring_doorbell/webrtcstream.py
webRTC stream will stop pinging after the `keep_alive_timeout` has passed. This is to prevent the stream from being kept alive indefinitely on a client disconnection.
=> Enable keep alive for webrtc stream

ring_doorbell/cli.py, ring_doorbell/stickup_cam.py
`ring-doorbell light -dn "Floodcam" on`
=> Add light command to cli

ring_doorbell/doorbot.py
Fixes [HA issue 128180](https://github.com/home-assistant/core/issues/128180)
=> Fix doorbell elite missing capabilities
