- ring_doorbell/__init__.py
**Description**
Allows to filter history by event kind: 'motion', 'on_demand', 'ding'
**Examples**
```python
In [13]: len(mydoorbell.history(limit=100))
Out[13]: 100
In [14]: len(mydoorbell.history(limit=100, kind='motion'))
Out[14]: 55
In [15]: len(mydoorbell.history(limit=100, kind='ding'))
Out[15]: 20
In [16]: len(mydoorbell.history(limit=100, kind='on_demand'))
Out[16]: 25
```
> Allows to filter history by event kind: 'motion', 'on_demand', 'ding'

- README.rst
- ring_doorbell/__init__.py
- ring_doorbell/const.py
- ring_doorbell/utils.py
- tests/test_ring.py
**Description**:
This PR allows the user to modify the chime wave sound for motion and ding for an external Ring chime. 
For example:
```python
from ring_doorbell import Ring
myring = Ring('foo@bar', 'secret')
chime = myring.chimes[0]
chime.name
'Downstairs'
chime.ringtone_ding
'Ding-Dong'
chime.ringtone_motion
'Upbeat'
chime.ringtones_ding_available
['Charge!',
'Ding-Dong',
'Dogs Barking',
'Doorbot',
'Flashback',
'Harp',
'Navi',
'Ring Alert 2',
'Ring Alert 3',
'Ring Default',
'Train Whistle',
'Triangle',
'Upbeat',
'Xylophone']
chime.ringtone_ding = 'Train Whistle'
chime.update()
chime.ringtone_ding
'Train Whistle'
```
**Fixes issue**: https://github.com/tchellomello/python-ring-doorbell/issues/19
> Added ability to change chime ringtones for motion and dings

- ring_doorbell/__init__.py
```python
File "/home/hass/.homeassistant/custom_components/binary_sensor/ring.py", line 129, in update
self._data.check_alerts(cache=self._cache)
File "/home/hass/.homeassistant/deps/ring_doorbell/__init__.py", line 375, in check_alerts
resp = self._ring.query(url)[0]
TypeError: 'NoneType' object is not subscriptable
```
> Fixes traceback when response is not a list.

- ring_doorbell/__init__.py
- tests/test_ring.py
Note that the device will be read-only, however operation such as history
will work as expected. Operation like changing the chime and volume
are not allowed.
```python
from ring_doorbell import Ring
shared_ring = Ring('foor@bar', 'secret')
print(shared_ring.devices)
{'chimes': [], 'doorbells': [<RingDoorBell: Front Door>]}
shared_doorbell = shared_ring.doorbells[0]
shared_doorbell.id = 12345
```
**Fixes issue**: https://github.com/tchellomello/python-ring-doorbell/issues/31
> Added the ability to load devices shared to the Ring account. Fixes issue #31

- ring_doorbell/__init__.py
- ring_doorbell/const.py
- ring_doorbell/utils.py
- tests/test_ring.py
- tests/test_ring_utils.py
Make session token reusable across multiple object instances via cache file.
With this patch, we can have more than one Ring object pointing to the same cache file
to share credentials to avoid multiple authentications.
If a different account is being informed, the cache file is regenerated.
This fix some issues of Ring accounts being disabled due to multiple auths.
> Make session token reusable

- README.rst
- ring_doorbell/__init__.py
- ring_doorbell/const.py
Changes the test_sound property to be a function.
Fixes Issue #28.
Please let me know if this change needs to be backward compatible. I can make it another property in that case. (Also thanks for the pointer on mitmproxy, worked like a charm!)
> chime: Support playing motion test sound

- ring_doorbell/__init__.py
Fixed __init__() methods on all Ring classes to handle it correctly. 
There was no need to override the RingGeneric method since all the others one will inherit the same method signature.
Fixes issue: #49
> Refactored methods to don't override __init__ from RingGeneric

- ring_doorbell/doorbot.py
- tests/test_ring.py
Allow the user to call `history()` to select a specific number of events of a given kind. 
**Fixes**: #45 
```python
from ring_doorbell import Ring
myring = Ring('user', 'password')
doorbell = myring.doorbells[0]
[z.get('kind') for z in doorbell.history(limit=3)]
['motion', 'motion', 'motion']
[z.get('kind') for z in doorbell.history(limit=3, kind='ding')]
[] 
[z.get('kind') for z in doorbell.history(limit=3, kind='ding', enforce_limit=True)]
['ding', 'ding', 'ding']
[z.get('kind') for z in doorbell.history(limit=3, kind='ding', enforce_limit=True, retry=1)]
WARNING:ring_doorbell.doorbot:Could not find total of 3 of kind ding
[]
[z.get('kind') for z in doorbell.history(limit=3, kind='ding', enforce_limit=True, retry=4)]
WARNING:ring_doorbell.doorbot:Could not find total of 3 of kind ding …
```
> Allows history to enforce to return minimum number of events for a given type

- ring_doorbell/doorbot.py
- scripts/ringcli.py
- Added ability to pass the parameter 'older_than' to history() method
- Added script which allows count the number of videos and download them
```bash
scripts/ringcli.py -u foo -p bar --count
---------------------------------
Ring CLI
---------------------------------
Counting videos linked on your Ring account.
This may take some time....
Total videos: 384
Ding triggered: 32
Motion triggered: 340
On-Demand triggered: 12
======================
---------------------------------
Ring CLI
---------------------------------
scripts/ringcli.py -u foo -p bar --count
1/384 Downloading 2017-11-14_00.57.16+00.00_motion_answered_64880679462719.mp4
2/384 Downloading 2017-11-13_21.32.23+00.00_motion_not_answered_64880151491.mp4
======================
scripts/ringcli.py --help
usage: ringcli.py [-h] …
```
> Allows `older_than` parameter to history() method

- ring_doorbell/doorbot.py
- tests/test_ring.py
Added a layer to verify if the account has an active subscription. 
```bash
In [12]: not_subscription.recording_url(not_subscription.last_recording_id)
Out[12]: False
In [13]: has_subscription.recording_url(has_subscription.last_recording_id)
Out[13]: 'https://ring-transcoded-videos.s3.amazonaws.com/6490927797489893075.mp4?X-Amz-Expires=3600&X-Amz-Date=20171121T230526Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJU3<REDACTED>.....'
In [14]: has_subscription.has_subscription
Out[14]: True
In [15]: not_subscription.has_subscription
Out[15]: False
```
Fixes: #71 
Mentioned by: https://github.com/home-assistant/home-assistant/issues/10736
> Added controllter to verify if account has subscription

- ring_doorbell/__init__.py
- tests/test_base.py
This method will call recursively all devices linked to the Ring account and update its attributes. 
Fixes: #74 
```python
from ring_doorbell import Ring
myring = Ring('foo', 'bar')
myring.update()
```
> Created generic update method for all devices on Ring top-parent object

- ring_doorbell/__init__.py
- setup.py
- tests/test_base.py
* Added generic method `update()` on the top level  `Ring` method that refreshes the attributes for all linked devices. #75
> Version 0.1.9

- ring_doorbell/__init__.py
move the _save_cache(self.cache, self.cache_file) inside the if statement
so when we are not reusing the session it does not attempt to persist the 
token to disk.  This resolves issue #79
> only save token to disk if reuse session is true

- ring_doorbell/doorbot.py
Fixes #86 
Make sure battery_life argument exists before comparison
```
value = int(self._attrs.get('battery_life'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
> Make sure battery_life argument exists before comparison

- ring_doorbell/chime.py
- ring_doorbell/doorbot.py
Fixes battery_life attribute because sometimes the JSON return a str instead of an int
Fixes: #91 
```python
>>>from ring_doorbell import Ring
>>>from pprint import pprint
>>>myring = Ring('user', 'pass', 'true')
>>>obj = myring.doorbells[0] #Front Door door bell
>>>pprint(vars(obj))
{'_attrs': {u'address': u'address',
u'alerts': {u'connection': u'online'},
u'battery_life': u'58',
u'description': u'Front Door',
....
'_health_attrs': {u'average_signal_category': u'good',
u'average_signal_strength': -49,
u'battery_percentage': u'58',
u'battery_percentage_category': u'good',
u'battery_voltage': None,
u'battery_voltage_category': None,
u'firmware': u'Up to Date',
>>>print(obj.battery_life)
100
>>>print (obj._attrs["battery_life"])
58
>>>print(obj._health_attrs.get('battery_percentage'))
58 …
```
> Fixes battery_life attribute because sometimes the JSON return a str instead of an int

- ring_doorbell/doorbot.py
I have the latest generation stickup cam which has the option to be externally powered. This results in the batter life being None. I modified the code to return 0 for the battery in this case.
> support of externally powered new stickup cam

- ring_doorbell/const.py
I am not sure if anything else is needed but I found that adding these values allowed for certain capabilities to register properly.
There is also a Door View device which registers as `doorbell_portal` and allows the user to detect door knocks under the `Kind` `door_activity` but it seems all doorbells show this attribute so I am not sure how to distinguish it properly.  If anyone has any suggestions on how to add this properly that would be best.  Until then there is a small modification to add to Home Assistant that shows the knock sensor but it shows up for all doorbells which is not desirable.
> Add a couple of device kinds

- ring_doorbell/const.py
- ring_doorbell/doorbot.py
- ring_doorbell/stickup_cam.py
Related to #135, I added additional device kinds for new products based on the latest Ring App APK. This also includes adding the new knock detection capability check for the Peephole Cam.
Although, this should covers all the recent Ring product changes. From parsing the APK, it seems that the new Stick Up Cam is using the same device kind `cocoa_camera` for the battery and wire-in models. At this point, I am not sure how the app is able to differentiate them.
Moreover, there is a device kind called `doorbell_scallop` which could be the latest generation Doorbell 2 product but it's hard to tell. One thing for sure is that it is a battery operated product. Therefore, I omitted this device kind for the time being.
Finally, the 2nd generation of the Stick Up Cam Elite is identified as …
> Add additional device kinds for new products

- setup.py
Ensure both places are consistent to avoid install problems.
Fixes: #157
> Make consistent requirements.txt and setup.py

- .gitignore
- ring_doorbell/auth.py
Looks like the user agent was blocked by Ring again.  This is a temp fix that adds the HEADERS back into the auth class for the fetch/refresh token methods.  #174 
Also have #175 as a draft PR for the future.
> Blocked user agent temp fix

- ring_doorbell/const.py
To prevent time-out with the home-assistant ring component..
See also https://github.com/home-assistant/home-assistant/pull/30666
> Increased timeout from 5 to 10 seconds

- ring_doorbell/auth.py
- test.py
Removed the otp_callback and made is otp_code as a str.
Moved the private fetch_token logic into the public method, removed private method.  
MissingTokenError to be caught by calling client.
@balloob I also have an edit for the update-ring branch in HA, I can submit a PR on this as well.  
https://github.com/steve-gombos/home-assistant/tree/upgrade-ring
> Removed otp_callback

- .travis.yml
- README.rst
- requirements_tests.txt
- scripts/ringcli.py
- setup.py
- test.py
- tox.ini
- Removed python 2.7 and python 3.5.  Min python 3.6+.
- Updated the README (#188 and #190)
- Updated test.py examples for the data refactor that @balloob had previously done. (#186 and #189)
> Drop python 2.7/3.5. Updated readme and test.py examples

- ring_doorbell/doorbot.py
- scripts/ringcli.py
Fixes bug in ringcli.py causing flake8 error
Fixes bug when running pylint test with the following error:
"************* Module ring_doorbell.doorbot
ring_doorbell\doorbot.py:46:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)"
> Fix Build Errors

- ring_doorbell/doorbot.py
Saw some older comments on how to fix `get_snapshot` gave it a spin myself with some modified code in HA and to my surprise it worked.  It does seem like we get undesired results at times but the snapshots do indeed come through.
https://github.com/tchellomello/python-ring-doorbell/issues/147#issuecomment-569485663
https://github.com/tchellomello/python-ring-doorbell/issues/178#issuecomment-583767379
https://github.com/tchellomello/python-ring-doorbell/issues/181#issuecomment-574710982
Should also close: #124 i think too
Code I used in HA for testing `homeassistant/components/ring/camera.py`
Changed lines 111-113 from:
```
image = await asyncio.shield(
ffmpeg.get_image(self._video_url, output_format=IMAGE_JPEG,)
)
```
to
```
image = self._device.get_snapshot()
```
Results in, snapshots …
> Fix get snapshot based on comments

- ring_doorbell/__init__.py
- ring_doorbell/auth.py
- ring_doorbell/const.py
This fixes the issue where Ring reports a new device for every session
made by this library.
By having the same hardware ID per request, and by also associating it
with the initial auth request, we can group all calls as a single "device"
within the ring app. This allows users to properly track account
usage.
The cause of this issue is the fact that right now, create_session() generates
a new UUID every time it's referenced. We also don't associate a hardware_id
with the fetch_token() currently, even though this is valid for that request. This
was found by looking through the source code of the node ring module at 
https://github.com/dgreif/ring/blob/master/api/rest-client.ts#L161
> fix: prevent multiple device entries for "Python" in the Ring app when using this library

- ring_doorbell/doorbot.py
If a camera has no battery, return `None` instead of 0 to indicate that there is no battery available.
btw, right now battery_life 1 and 2 are summed if there are 2 battery bays. But shouldn't the result then also be divided by 2? So 2 full batteries is 100, while now it would be 200 ?
> Return None if no battery installed

- ring_doorbell/doorbot.py
Was getting 405 Client Error before because it looks like the endpoint (https://api.ring.com/clients_api/snapshots/timestamps?api_version=9) no longer accepts GET requests. Changed the initial snapshot request to a POST request to get it working.
Also added filename in arguements and download snapshot as jpg file to better match the function description """Take a snapshot and download it"""
> Fixed RingDoorBell.get_snapshot() and added download

- .github/workflows/ci.yml
Something is screwy with coveralls in `0.7.0` branch PR. ~~Going to try swapping to their GH Action to see if that helps.~~ Will PR to `master` first and we can rebase the `0.7.0` branch accordingly.
Looks like this is a [known issue](https://github.com/TheKevJames/coveralls-python/issues/251) in the `coveralls-python` package, and just adding the `--service` param fixes it.
> [dist] Fix coveralls build issue

- ring_doorbell/const.py
Recognizes device kind for recent generation of Ring Floodlight Cameras, as of June 2021.
> Recognize cocoa_floodlight as a floodlight kind

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- pylintrc
- ring_doorbell/doorbot.py
- ring_doorbell/generic.py
- ring_doorbell/group.py
- scripts/ringcli.py
- tox.ini
Trying to get a separate PR together to add motion_detection_enabled switching and encountered issues with the current CI pipeline being broken due to older unsupported python versions 3.6 and 3.7.  This PR updates CI.yaml and tox.ini to bring them up to date.  It also fixes linting issues in the codebase and includes a pre-commit-config.yaml to prevent new linting issues.
> Fix ci to use up to date python versions and include pre-commit-config

- ring_doorbell/auth.py
- ring_doorbell/const.py
- ring_doorbell/doorbot.py
- ring_doorbell/stickup_cam.py
- test.py
- tests/fixtures/ring_devices.json
- tests/test_ring.py
Allows switching off and on of the motion detection.  
The principal use case for this is for indoor cams to turn on automatically when leaving the house or at night but not to be recording when family are around.  N.B. I have an update ready for homeassistant to use this feature.
Feature mentioned in feature request  https://github.com/tchellomello/python-ring-doorbell/issues/126 and solution provided by @jsetton in the same issue.
> Add motion detection enabled switch

- README.rst
- poetry.lock
- pyproject.toml
- ring_doorbell/__init__.py
- ring_doorbell/cli.py
- ring_doorbell/const.py
- ring_doorbell/ring.py
- ring_doorbell/stickup_cam.py
- scripts/ringcli.py
- test.py
This PR fixes some issues with the cli and updates the documentation:
- If the existing token_cash is invalid then reauthorise
- Update the previous ringclip.py to call ring_doorbell/cli with `videos` option and mark as deprecated
- Update test.py to call ring_doorbell/cli and mark as deprecated
- Update cli to use asyncclick
- Update README to contain cli instructions
- Move Ring class out of `__init__.py` into its own module
- Tests still to be added
> Fix and update cli

- ring_doorbell/__init__.py
- ring_doorbell/auth.py
- ring_doorbell/cli.py
- ring_doorbell/exceptions.py
- ring_doorbell/listen.py
- tests/test_cli.py
Add custom exceptions to encapsulate oauth/token related errors away from consumers and handle situations where tokens are invalidated on the ring website and queries return 401 errors.  As this is a breaking change for consumers currently handling oauthlib.oauth2 errors directly it will go into a new minor release.
> Add custom exceptions and encapsulate oauth error handling

- pyproject.toml
- ring_doorbell/const.py
- ring_doorbell/doorbot.py
- ring_doorbell/stickup_cam.py
Add the following missing devices and updates some of the incorrect device naming:
stickup_cam_wired - new elite
stickup_cam_mini_v2 - new indoor
lpd_v3 - missing doorbell pro
doorbell_graham_cracker- missing doorbell wired
cocoa_doorbell_v2 - new 2nd Gen
doorbell_oyster - missing doorbell 4
cocoa_spotlight - new spotlight plus
> Add ring devices and bump version to 0.8.2

- README.rst
There was a typo while I was reading the documentation. I assumed it should have said "Ring" and not "ding"
> fix typo in the documentation

- ring_doorbell/const.py
- ring_doorbell/listen/eventlistener.py
- ring_doorbell/ring.py
- tests/fixtures/ring_listen_intercom_unlock.json
- tests/test_listen.py
Handle the ring intercom door unlock event and `log.debug` on unknown events instead of warning
> Handle Intercom unlock event

- .github_changelog_generator
- CHANGELOG.md
- pyproject.toml
[Full Changelog](https://github.com/tchellomello/python-ring-doorbell/compare/0.8.12...0.9.0)
**Release highlights:**
- Async support for the library
- Removed python 3.8 support
**Breaking changes:**
- Synchronous api calls are now deprecated.  For example calling `Ring.update_data()` will emit a deprecation warning to use `await Ring.async_update_data()` which should be run within an event loop via `asyncio.run()`.  See `test.py` for an example.
- Calling the deprecated sync api methods from inside a running event loop is not supported.  This is unlikely to affect many consumers as the norm if running in an event loop is to make synchronous api calls from an executor thread.
- Python 3.8 is no longer officially supported and could break in future releases.
**Breaking change pull …
> Prepare 0.9.0

- CHANGELOG.md
- pyproject.toml
[Full Changelog](https://github.com/tchellomello/python-ring-doorbell/compare/0.9.0...0.9.1)
Hotfix for missing typing_extensions dependency
**Fixed bugs:**
- Fix missing typing\_extensions dependency [\#413](https://github.com/tchellomello/python-ring-doorbell/pull/413) (@sdb9696)
**Project maintenance:**
- Update contributing docs to remove tox step [\#411](https://github.com/tchellomello/python-ring-doorbell/pull/411) (@sdb9696)
- Update and add code checkers [\#410](https://github.com/tchellomello/python-ring-doorbell/pull/410) (@sdb9696)
> Prepare 0.9.1

- poetry.lock
- pyproject.toml
- ring_doorbell/cli.py
- ring_doorbell/const.py
- ring_doorbell/doorbot.py
- ring_doorbell/listen/eventlistener.py
- ring_doorbell/other.py
- ring_doorbell/ring.py
- tests/conftest.py
- tests/fixtures/ring_listen_credentials.json
- tests/test_cli.py
- tests/test_listen.py
The deprecated [fcm api](https://firebase.google.com/docs/cloud-messaging/migrate-v1) stopped the event listener working.
This PR migrates to the new version of firebase-messaging to support the new FCM HTTP v1 api.
> Fix event listener

- ring_doorbell/const.py
- ring_doorbell/doorbot.py
- tests/test_ring.py
I am currently working on adding code to the Home Assistant ring core component to support `async_set_existing_doorbell_type` and `async_set_existing_doorbell_type_enabled`. In working on the switch to enable/disable the in-home chime, I found that Ring is expecting a string, not a boolean value. Error below:
> ring_doorbell.exceptions.RingError: Unknown error during query of url https://api.ring.com/clients_api/doorbots/<doorbell id removed>: Invalid variable type: value should be str, int or float, got True of type <class 'bool'>
Ring is expecting 0 or 1 when enabling and disabling.  I have tested the code change with a modified test.py with the following body between `await ring.async_update_data()` and `await auth.async_close()`
```
devices = ring.devices() …
```
> Fix method to enable in-home doorbell chime

- .github/workflows/ci.yml
- .github/workflows/locks-threads.yml
- .github/workflows/stale.yml
- .github_changelog_generator
- CHANGELOG.md
- CONTRIBUTING.rst
- README.rst
- pyproject.toml
Repo has been moved from `https://github.com/tchellomello/python-ring-doorbell` to `https://github.com/python-ring-doorbell/python-ring-doorbell`
> Migrate repo to python-ring-doorbell github organisation

- poetry.lock
- pyproject.toml
Asyncclick correctly specifies the dependency starting with version 8.1.7.1.
> Remove anyio from dependencies

- README.rst
The following updates have been made to the the readme:
- Corrected the two readthedocs contributing links
- Changed the test.py and test_sync.py links to be explicit. They worked in github but 404ed on readthedocs
> Fix broken links in readme

- ring_doorbell/const.py
- ring_doorbell/doorbot.py
- tests/test_ring.py
`async_set_existing_doorbell_type_duration` was checking for the duration to be between 0 and 11, but Ring only accepts 0 through 10 for duration.  I added a new set of min/max variables rather than using a different min/max set in order to allow more flexibility in the future.
Error from Ring when setting duration to 11:
```
ring_doorbell.exceptions.RingError: HTTP error with status code 422 during query of url https://api.ring.com/clients_api/doorbots/987652: 422, message='Unprocessable Entity', url='https://api.ring.com/clients_api/doorbots/987652?doorbot%5Bdescription%5D=Front+Door&doorbot%5Bsettings%5D%5Bchime_settings%5D%5Bduration%5D=11
```
> Fix in-home chime duration setter

- poetry.lock
- pyproject.toml
- ring_doorbell/const.py
- ring_doorbell/doorbot.py
- ring_doorbell/ring.py
- ring_doorbell/rtcstream.py
This PR lets the api start a webrtc streaming session. Requires a client that supports the webrtc protocol and can generate the sdp offer.
This should be considered experimental functionality until added to the docs.
> Add WebRTC live streaming session generation

- CHANGELOG.md
- pyproject.toml
- uv.lock
[Full Changelog](https://github.com/python-ring-doorbell/python-ring-doorbell/compare/0.9.3...0.9.4)
**Release highlights:**
- Migrate from poetry to uv for package management
- Bugfixes for in-home-chime
**Implemented enhancements:**
- Add WebRTC live streaming session generation [\#348](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/348) (@sdb9696)
**Fixed bugs:**
- Fix in-home chime duration setter [\#428](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/428) (@briangoldstein)
**Documentation updates:**
- Fix broken links in readme [\#426](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/426) (@briangoldstein)
**Project maintenance:**
- Migrate to uv and add testpypi publishing …
> Prepare 0.9.4

- .github/workflows/publish.yml
v3 due to be [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
> Upgrade artifact upload/download github actions

- CHANGELOG.md
- pyproject.toml
- uv.lock
[Full Changelog](https://github.com/python-ring-doorbell/python-ring-doorbell/compare/0.9.4...0.9.5)
**Release highlights:**
- New CLI commands
- Enhancement to the experimental WebRTC stream feature
**Implemented enhancements:**
- Enable multiple webrtc sessions per device [\#440](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/440) (@sdb9696)
- Add cli command to open door on intercom [\#438](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/438) (@sdb9696)
- Add in-home chime support to CLI [\#427](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/427) (@briangoldstein)
**Fixed bugs:**
- Fix max. volume of Ring Chime device. [\#439](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/439) (@daniel-k)
- Fix cli listen …
> Prepare 0.9.5

- ring_doorbell/auth.py
The ring oath endpoint now requires the `client_id` to be sent with initial token request. This change means all prior versions of this library will no longer work.
> Send client_id with oauth fetch tokens request

- ring_doorbell/auth.py
- ring_doorbell/cli.py
- ring_doorbell/generic.py
- ring_doorbell/group.py
- ring_doorbell/ring.py
Consumers still using deprecate attributes will now start getting type checker errors.
> Do not expose deprecated attributes to type checkers

- ring_doorbell/chime.py
- ring_doorbell/cli.py
- ring_doorbell/doorbot.py
- ring_doorbell/listen/eventlistener.py
- ring_doorbell/other.py
- ring_doorbell/stickup_cam.py
Consumers should call refresh devices themselves after calling setters. This allows consumers to control when they call `async_update_devices` in order to allow time for the device to return the new value correctly.
> Do not refresh devices after calling setters

- ring_doorbell/auth.py
- tests/conftest.py
Send `hardware_id` in all requests. Could fix [ha issue 128252](https://github.com/home-assistant/core/issues/128252).
> Add hardware_id to all requests

- ring_doorbell/auth.py
- tests/test_other.py
- tests/test_ring.py
Ring servers suddenly required a null json value for `PUT` requests.
> Fix 422 errors on PUT requests

- ring_doorbell/event.py
- ring_doorbell/listen/eventlistener.py
- tests/test_cli.py
Will enable consumers to filter out multiple events being raised by battery doorbells.
> Add is_update flag to ring events for updated events

- CHANGELOG.md
- pyproject.toml
- uv.lock
[Full Changelog](https://github.com/python-ring-doorbell/python-ring-doorbell/compare/0.9.10...0.9.11)
**Implemented enhancements:**
- Add is\_update flag to ring events for updated events [\#467](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/467) (@sdb9696)
> Prepare 0.9.11

- CHANGELOG.md
- pyproject.toml
- uv.lock
[Full Changelog](https://github.com/python-ring-doorbell/python-ring-doorbell/compare/0.9.9...0.9.12)
**Release highlights:**
- Fix for Ring Elite motion and ding events
- Add `is_update` to ring events to enable filtering duplicates
**Implemented enhancements:**
- Add is\_update flag to ring events for updated events [\#467](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/467) (@sdb9696)
**Fixed bugs:**
- Add new push notification intercom unlock [\#464](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/464) (@sdb9696)
- Fix doorbell elite missing capabilities [\#463](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/463) (@sdb9696)
**Project maintenance:**
- Update websockets dependency for \>=13 …
> Prepare 0.9.12
